### ISSUE TITLE
Selected button is not reset on iOS

### ISSUE THREAD

**Issue by Legioth** [samiheikki/javascript-guessing-game#11]
The most recently tapped answer button is shown with white text instead of green in Safari on iOS 10 on my iPad Air. On the same device, the button instead shows as green text on green background if opened in the embedded browser view from the official Twitter app.

**Comment by samiheikki** [comment]
Hey @Legioth 

I modified the buttons to use ripple effect instead. Should fix this issue. Thanks for your report!
