### ISSUE TITLE
Use github user name instead of real name in ranking

### ISSUE THREAD

**Issue by samiheikki** [samiheikki/javascript-guessing-game#112]
At least the firebase auth provides the screenName, but there seems not be any public api to get this.
<img width="777" alt="screen shot 2017-04-15 at 14 05 58" src="https://cloud.githubusercontent.com/assets/8615573/25063136/16e3d6f8-21e5-11e7-8a5c-906fe641e515.png">

**Comment by ghost** [comment]
@samiheikki 
Maybe you can use this package : https://github.com/sindresorhus/github-username
It will work only for users that listed their email publicly but there seems to be a PR that will solve it too:
https://github.com/sindresorhus/github-username/pull/5

**Comment by ghost** [comment]
The PR mentioned above was approved and github-username is working as expected when ran with node but I didn't manage to operate it inside Vue.js 😿

**Comment by hisabimbola** [comment]
Hello @samiheikki is help still needed here, I will like to fix this issue.

**Comment by samiheikki** [comment]
@hisabimbola Help is very much appreciated :) You can go ahead and do it 🎉

**Comment by hisabimbola** [comment]
Created a PR @samiheikki

let me know what you think

**Comment by samiheikki** [comment]
Cool thanks! I'll check it out later in more detail when I have time. Please ping me if I haven't responded in 48 hours :)
