### ISSUE TITLE
typo: RE-DOM should be RE:DOM

### ISSUE THREAD

**Issue by tunnckoCore** [samiheikki/javascript-guessing-game#115]

**Comment by zoltantothcom** [comment]
I know :-/ But the image names should be === to JSON entry, and *'re:dom.png'* is an invalid filename, so I chose to go with a dash. It might be a bigger issue/task/enhancement to allow titles different from image names..

**Comment by samiheikki** [comment]
Extending this PR, might be used for that too: https://github.com/samiheikki/javascript-guessing-game/pull/99

**Comment by pakastin** [comment]
I'm ok with RE-DOM 😎👍

**Comment by samiheikki** [comment]
Great 😎 I'll close the issue
