### ISSUE TITLE
Logos filenames should not be tool/library name

### ISSUE THREAD

**Issue by cosminlupu** [samiheikki/javascript-guessing-game#25]
It's very easy to get the answer right, when you can see the tool/library name in the logo's filename. See http://imgur.com/a/lf9sU or https://goo.gl/krmo1P. I suggest having the logos's filenames a a random string.

**Comment by ivan-gerasin** [comment]
yep! Found that too. Came here, to open issue for it.
File name might be hash from lib name + secret.

**Comment by vitaminniy** [comment]
I thought the point was in answering all the questions, not hacking the game ;)

**Comment by BojanKogoj** [comment]
Paste this in your console, and you will solve it within seconds

```
function solve() {
    setTimeout(function() {
        let logo = document.getElementsByClassName('logo')
        if (!logo)
            return;
        let btns = document.getElementsByTagName('button');
        for (let el in btns) {
            if (btns[el].textContent && btns[el].textContent.indexOf(logo[0].alt) >= 0) {
                btns[el].click();
                solve();
            }
        }
    }, 100);
}
solve();
```

Thought I would abuse this 'bug'

**Comment by samiheikki** [comment]
For me, this is not an issue. There are always people who'll cheat in these kind of games, and in this case it gives an ironic twist when you can cheat in a developer game with developer tools.

I added `help wanted` label, so if somebody wants to work on this, I'll merge the PR.

**Comment by radubogdan** [comment]
I thought the whole point is to use the inspector or some kind of wrongly defined global function.

**Comment by samiheikki** [comment]
Decided to fix this. Can you test how is it working now?

**Comment by samiheikki** [comment]
Just a note for me (this can be used in development environment):

```
function solve() {
    setTimeout(function() {
        let logo = document.getElementsByClassName('logo')
        if (!logo)
            return;
        let btns = document.getElementsByTagName('button');
        for (let el in btns) {
            if (btns[el].textContent && btns[el].textContent.toLowerCase().indexOf(logo[0].src.replace('http://localhost:8080/static/logos/', '').replace('.png', '')) >= 0) {
                btns[el].click();
                solve();
            }
        }
    }, 100);
}
solve();
```

**Comment by BojanKogoj** [comment]
And production version. 
```
function solve() {
    setTimeout(function() {
        let logo = document.getElementsByClassName('logo')
        if (!logo)
            return;
        let btns = document.getElementsByTagName('button');
        let name = logo[0].src.split("/").pop().split(".")[0]
        for (let el in btns) {
            if (btns[el].textContent && btns[el].textContent.indexOf(atob(name)) >= 0) {
                btns[el].click();
                solve();
            }
        }
    }, 100);
}
solve();
```
Though it does make it harder for someone to cheat

**Comment by samiheikki** [comment]
Well hardened it a bit for getting to high scores with cheating: https://github.com/samiheikki/javascript-guessing-game/commit/fd33dd9c9393e76f665a49a2d4fa77cea07002b7 Altough can be cheated by just increasing the setTimeout time. It is hard to prevent cheating in an open source project 😆
