### ISSUE TITLE
Add few more logos

### ISSUE THREAD

**Issue by tunnckoCore** [samiheikki/javascript-guessing-game#40]
JSTransformer - https://github.com/jstransformers/jstransformer
Rollup - https://github.com/rollup/rollup
PostHTML - https://github.com/posthtml/posthtml ([svg without the text](http://jsbin.com/luqozifefi/edit?html,output) make it png)
esnext - https://github.com/esnext/esnext/blob/gh-pages/favicon.ico (should zoom it and make it png)
Inquirer - https://github.com/SBoudrias/Inquirer.js/blob/master/assets/inquirer_small.png

The Toolkit - https://github.com/node-toolkit ([What is "The Toolkit"?](https://github.com/node-toolkit/getting-started) - core behind Assemble, and all below projects)
Base - https://github.com/node-base/base - the very core of AssembleJS
Generate - https://github.com/generate - better alternative to Yeoman, built on Base
Verb - [https://github.com/verbose/verb](https://github.com/verbose/verb/tree/dev) - docs build system built on Assemble & Generate
Update - https://github.com/update/update - code maintain automation, built on AssembleCore & Generate
Enquirer - https://github.com/enquirer - better alternative to Inquirer, built on Base
Assemble - https://github.com/assemble/assemble

**Comment by TheFrankemon** [comment]
I liked them all @tunnckoCore. By the way, I don't know if there are any guidelines for considering logos or not. For example the 32 logos I added, I found them using Google and imo most of them appear both on javascripting.com and npmjs.org. @samiheikki, do the logos have to have certain "popularity" reqs?

**Comment by samiheikki** [comment]
Not really any requirements :)

**Comment by tunnckoCore** [comment]
Cool.

**Comment by samiheikki** [comment]
Added few new logos: https://github.com/samiheikki/javascript-guessing-game/pull/43 But looks like nothing from this list.

**Comment by tunnckoCore** [comment]
We can add https://github.com/babel/babylon too ;p

**Comment by zoltantothcom** [comment]
I think this one can be closed - all the logos from this thread have been added. Cheers!

**Comment by samiheikki** [comment]
Super thanks to both of you @tunnckoCore and @zoltantothcom

**Comment by tunnckoCore** [comment]
awesome! thanks
