### ISSUE TITLE
Logo does not allways load after restart

### ISSUE THREAD

**Issue by fried-eggz** [samiheikki/javascript-guessing-game#62]
Like the title says. Sometimes the lib logo does not load when the game is restarted after failing to answer correctly. Refreshing the page solves this.

![image](https://cloud.githubusercontent.com/assets/5286334/24287451/1b8b6fb2-107a-11e7-9370-9580ff8c5cae.png)

Using Firefox 52.0.1 on Ubuntu 

![image](https://cloud.githubusercontent.com/assets/5286334/24287440/0588eed8-107a-11e7-9b59-d7f9ccc65854.png)

**Comment by samiheikki** [comment]
Thanks for the report. I'll fix this in the weekend.

**Comment by samiheikki** [comment]
Should be fixed with https://github.com/samiheikki/javascript-guessing-game/pull/68 Can you test?

**Comment by samiheikki** [comment]
PS. Firefox supports service workers so please force refresh

**Comment by fried-eggz** [comment]
Seems to work now. Nice job.
