### ISSUE TITLE
A better shuffle algorithm 

### ISSUE THREAD

**Issue by tunnckoCore** [samiheikki/javascript-guessing-game#71]
Hi again. I'm playing it almost every day, not because I don't know them, but just because for the fun, relax and switching context - something different than code for a bit ;d

In anyway, it's not just for me. Currently almost always when answer is correct, the answer of the next question is in the same place. Some more advanced algo would make it a bit harder to answer so fast.

I think it would be a lot better to have similar projects as answers. For example Redux, React, Preact and Electron has similar logos, so when the question is for redux logo, answers should be exactly these four, so then user would be forced to think for bit.

Another cool feature (maybe as separate website) may be to add timer and ranking :D Why not?

**Comment by samiheikki** [comment]
These are all good ideas, I've thought about all of them.

### Better suffle
It should be completely randomized where the right answer is and what are the 3 false options. I think a good addition would be that it last would not show previous logo as an option for the current answer options.

### Similar projects
As an idea, this is great. But I'm unable to create any automatized algorithm for similar logos. Those would need updated manually whenever adding a new logo, and I'm not a fan for that. More steps in PRs => Less PRs.

### Ranking
This has been my long term idea. Now that #25 is fixed, this could be the next step? What would your preferences in the ranking? My current idea is that you can (optionally) log in with GitHub account and your ranking would be shown when finishing the test. And you could see all the rankings in /ranking page etc. But main point, without a GitHub account, you could not make it into ranking.

**Comment by FezVrasta** [comment]
About .2, you may add a color matching algorithm, this should increase a bit the chance of showing correlated logos.

**Comment by samiheikki** [comment]
Good idea. Do you have any example that you could link to me?

And as for the ranking, I've already been building it in [ranking branch](https://github.com/samiheikki/javascript-guessing-game/tree/ranking). Nothing works yet in there, but hopefully in a few weeks I'll have the time to finish it.

**Comment by FezVrasta** [comment]
I never done something similar, but something like https://www.npmjs.com/package/get-image-colors should probably do the trick.

A step further would be to find similarities between the logos, I know of several libraries that do this kind of analysis but I never worked with them.

**Comment by samiheikki** [comment]
!!! RANKING: https://github.com/samiheikki/javascript-guessing-game/pull/110

**Comment by samiheikki** [comment]
Shuffle is now also improved: https://github.com/samiheikki/javascript-guessing-game/commit/c2c51e3bacfd84a3abb7220f479d09e5ac932ab2

**Comment by FezVrasta** [comment]
May you show the GitHub nickname instead/along the name in the high rank list?

**Comment by samiheikki** [comment]
That was my aim, but github login doesn't provide github nickname. Only "display name", email and img url

**Comment by FezVrasta** [comment]
Umh... it seems weird.

**Comment by samiheikki** [comment]
I'm using firebase for authentication, it may strip the oauth response from "unnecessary data".

**Comment by samiheikki** [comment]
Actually, there might be a way to get these: https://firebase.google.com/docs/auth/web/github-auth I'll change to github nickname if I can

**Comment by samiheikki** [comment]
Well unable to do it atm, creating a separate issue with help wanted label #112

**Comment by tunnckoCore** [comment]
awesome, i will try when get some time

**Comment by tunnckoCore** [comment]
I don't see any link for ranking, or it is at the end? huh

edit: and also "shuffle algo"  not seems better

**Comment by samiheikki** [comment]
Service workers caches the app pretty well, use force refresh cmd + shift + r
