### ISSUE TITLE
TravisCI doesn't qualify

### ISSUE THREAD

**Issue by zoltantothcom** [samiheikki/javascript-guessing-game#85]
IMO TravisCI is not directly related to JS. It's a great tool that *can* be used for JS projects, but for many others as well.  I think it should be removed from the list of JavaScript libs/frameworks.

**Comment by samiheikki** [comment]
Sure, go ahead

**Comment by samiheikki** [comment]
Fixed in https://github.com/samiheikki/javascript-guessing-game/commit/2c307efc187055b34589c2a9e14cdeb6b2acee6e

**Comment by tunnckoCore** [comment]
If we should be correct this applies also for couple of more logos - CodeClimate, Vaadin and etc. 

I believe we should not remove them, since they all are related to the javascript development and community.

**Comment by zoltantothcom** [comment]
@tunnckoCore  then we can add a gazillion of related tools - all the CI-s, code coverage reporters, text editors and IDE-s (Atom even kind of makes sense 'cause written in js :) ), even preferred node hosting providers? all of those are *somewhat* related to javascript development, but shouldn't we keep it clean here? just asking.. otherwise we are looking at over 9000 logos to add :)

**Comment by samiheikki** [comment]
I prefer to keep it JavaScript related. But a line for acceptable/not is difficult to make. For example Vaadin: Vaadin Framework is not JS-related, Vaadin Elements is JS-related. But in the case of Travis, I think it is quite clear that it is not JS-related cause it is built with JS or should only be used with JS projects.
