### ISSUE TITLE
Allow Adding more meta to logos.json

### ISSUE THREAD

**Issue by pi0** [samiheikki/javascript-guessing-game#98]
Hi :) Thanks for this nice game.I'm going to add a couple of logos now, but when i was playing game, i expected to get a link to that library i don't know, possibly with adding a simple "url" field to logos.json. If you are ok with this i can open a PR for adding this link to UI too :)

**Comment by samiheikki** [comment]
So in the result page there would be a link to that library you missed? I like the idea, I would merge.

**Comment by samiheikki** [comment]
Fixed in #181
